name: Release

on:
  push:


jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          
      - name: Build Docker image
        run: docker build Listify-Backend --tag jelmerr/s3-ips-jelmer:$(date +%s)

      - name: Docker push
        run: docker push jelmerr/s3-ips-jelmer
